# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tBhPoPlgKGxzefGGQVvba0wukUOHKRH2
"""

!pip install scikit-learn

import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from sklearn.cluster import KMeans
import pandas as pd

# ===============================
# SETTINGS
# ===============================

NUMBER_OF_TRANSFORMERS = 6
TRANSFORMER_CAPACITY_KW = 400
PIXEL_TO_METER = 2   # 1 pixel = 2 meters

# ===============================
# LOAD FILES
# ===============================

image_path = "/content/map.png"
csv_path = "/content/houses.csv"

img = Image.open(image_path)

data = pd.read_csv(csv_path)
houses = data[['x', 'y']].values
loads = data['load_kw'].values

# ===============================
# K-MEANS CLUSTERING
# ===============================

kmeans = KMeans(n_clusters=NUMBER_OF_TRANSFORMERS, random_state=0)
labels = kmeans.fit_predict(houses)
centroids = kmeans.cluster_centers_

# ===============================
# CAPACITY CHECK
# ===============================

transformer_loads = np.zeros(NUMBER_OF_TRANSFORMERS)

for i in range(len(houses)):
    transformer_loads[labels[i]] += loads[i]

print("\nTransformer Load Summary:")
for i in range(NUMBER_OF_TRANSFORMERS):
    print(f"Transformer {i+1}: {transformer_loads[i]:.2f} kW")

    if transformer_loads[i] > TRANSFORMER_CAPACITY_KW:
        print("⚠ Capacity Exceeded!")

# ===============================
# TOTAL CABLE LENGTH
# ===============================

total_length_pixels = 0

for i in range(len(houses)):
    total_length_pixels += np.linalg.norm(
        houses[i] - centroids[labels[i]]
    )

total_length_meters = total_length_pixels * PIXEL_TO_METER

print("\nTotal Cable Length:", round(total_length_meters, 2), "meters")

# ===============================
# VISUALIZATION
# ===============================

plt.figure(figsize=(10,6))
plt.imshow(img)

plt.scatter(houses[:,0], houses[:,1])
plt.scatter(centroids[:,0], centroids[:,1], marker='X', s=300)

for i in range(len(houses)):
    plt.plot(
        [houses[i][0], centroids[labels[i]][0]],
        [houses[i][1], centroids[labels[i]][1]]
    )

plt.title("Smart Transformer Placement with Capacity Check")
plt.axis("off")
plt.show()

import os
print("Files in current directory after upload:")
print(os.listdir('.'))